name: Demo Secrets in Different Environments

# Triggers: On push to 'dev' or 'main' branches
on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy-dev:
    # Conditional: Run only on 'dev' branch
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    # Target the 'development' environment (assume created in repo settings with secrets)
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use dev secret (e.g., for deployment)
        run: |
          echo "Deploying to dev environment using API key: ${{ secrets.API_KEY_DEV }}"
          # Simulate deployment: curl -H "Authorization: Bearer ${{ secrets.API_KEY_DEV }}" https://dev-api.example.com/deploy

      - name: Clean up (optional post-deploy step)
        run: echo "Dev deployment complete."

  deploy-prod:
    # Conditional: Run only on 'main' branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # Target the 'production' environment (assume created in repo settings with secrets)
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use prod secret (e.g., for deployment)
        run: |
          echo "Deploying to prod environment using API key: ${{ secrets.API_KEY_PROD }}"
          # Simulate deployment: curl -H "Authorization: Bearer ${{ secrets.API_KEY_PROD }}" https://prod-api.example.com/deploy

      - name: Clean up (optional post-deploy step)
        run: echo "Prod deployment complete."
